/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-03-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   02-02-2021   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
public class skedConstants {
    public static final string JOB_STATUS_PENDING_ALLOCATION = 'Pending Allocation';
    public static final string JOB_STATUS_DISPATCH = 'Dispatched';
    public static final string JOB_STATUS_READY = 'Ready';
    public static final string JOB_STATUS_COMPLETE = 'Complete';
    public static final string JOB_STATUS_CANCELLED = 'Cancelled';

    public static final string JA_STATUS_PENDING_DISPATCH = 'Pending Dispatch';
    public static final string JA_STATUS_DISPATCH = 'Dispatched';
    public static final string JA_STATUS_CONFIRMED = 'Confirmed';
    public static final string JA_STATUS_COMPLETE = 'Complete';
    public static final string JA_STATUS_DECLINED = 'Declined';
    public static final string JA_STATUS_DELETED = 'Deleted';

    public static final string JOB_TYPE_VIRTUAL = 'Virtual';
    public static final string JOB_TYPE_IN_PERSON = 'In-Person';
    public static final string JOB_TYPE_CALL = 'Call';

    public static final string APPOINTMENT_TYPE_VIRTUAL = 'Virtual';
    public static final string APPOINTMENT_TYPE_IN_PERSON = 'In Person';
    public static final string APPOINTMENT_TYPE_CALL = 'Call';

    public static final string EVENT_STATUS_OPEN = 'Open';
    public static final string EVENT_STATUS_CLOSED_COMPLETE = 'Closed - Completed';
    public static final string EVENT_STATUS_CLOSED_NOT_COMPLETED = 'Closed - Not Completed';

    public static final string SESSION_DELIVERED_QUESTION = 'Which session would you like to book';
}